// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/24/2026, 5:20:01 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/believe/Work/lxpath/admin/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/believe/Work/lxpath/admin/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/believe/Work/lxpath/admin/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/believe/Work/lxpath/admin/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/believe/Work/lxpath/admin/app/plugins/**/*.{js,ts,mjs}","/Users/believe/Work/lxpath/admin/app/composables/**/*.{js,ts,mjs}","/Users/believe/Work/lxpath/admin/app/utils/**/*.{js,ts,mjs}","/Users/believe/Work/lxpath/admin/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/believe/Work/lxpath/admin/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/believe/Work/lxpath/admin/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/believe/Work/lxpath/admin/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;